services:
  - type: web
    name: task-management-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://<YOUR_DB_HOST>:3306/task_management_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - key: SPRING_DATASOURCE_USERNAME
        value: <YOUR_DB_USERNAME>
      - key: SPRING_DATASOURCE_PASSWORD
        value: <YOUR_DB_PASSWORD>
      - key: JWT_SECRET
        value: <YOUR_JWT_SECRET>
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_JPA_SHOW_SQL
        value: "true"
      - key: SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL
        value: "true"
      - key: SERVER_PORT
        value: "8081"
      - key: SERVER_SERVLET_CONTEXT_PATH
        value: /api
